# Generated by Django 4.1.1 on 2022-10-04 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_customer'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Customer',
            new_name='Client',
        ),
    ]
